animationRange = (interval 0f 4325f)
rotazionesbarra = eulerangles 0 90 0
mappac = Uvwmap()
mappac.maptype = 1
mappac.length = 2.2
mappac.width = 2.2
mappac.height = 2.4
utile = 2
foo = Cylinder name:"sbarra_1_1" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_2" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_3" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_4" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_5" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_6" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_7" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_8" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_9" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_10" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_11" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_12" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_13" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_14" radius:1.0 height:90.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_15" radius:1.0 height:600.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_16" radius:1.0 height:600.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_17" radius:1.0 height:600.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_18" radius:1.0 height:600.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_19" radius:1.0 height:600.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_1_20" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_1" radius:1.0 height:425.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_2" radius:1.0 height:425.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_3" radius:1.0 height:425.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_4" radius:1.0 height:425.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_5" radius:1.0 height:425.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_6" radius:1.0 height:95.5 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_7" radius:1.0 height:95.5 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_8" radius:1.0 height:95.5 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_9" radius:1.0 height:95.5 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_10" radius:1.0 height:95.5 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_11" radius:1.0 height:95.5 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_12" radius:1.0 height:95.5 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_13" radius:1.0 height:95.5 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_14" radius:1.0 height:95.5 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_15" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_16" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_17" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_18" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_19" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_2_20" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_1" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_2" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_3" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_4" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_5" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_6" radius:1.0 height:200.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_7" radius:1.0 height:200.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_8" radius:1.0 height:200.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_9" radius:1.0 height:200.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_10" radius:1.0 height:200.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_11" radius:1.0 height:200.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_12" radius:1.0 height:200.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_13" radius:1.0 height:200.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_14" radius:1.0 height:200.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_15" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_16" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_17" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_18" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_19" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_3_20" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_1" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_2" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_3" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_4" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_5" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_6" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_7" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_8" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_9" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_10" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_11" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_12" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_13" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_14" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_15" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_16" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_17" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_18" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_19" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_4_20" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_1" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_2" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_3" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_4" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_5" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_6" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_7" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_8" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_9" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_10" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_11" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_12" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_13" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_14" radius:1.0 height:300.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_15" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_16" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_17" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_18" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_19" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_5_20" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_1" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_2" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_3" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_4" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_5" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_6" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_7" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_8" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_9" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_10" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_11" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_12" radius:1.0 height:0.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_13" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_14" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_15" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_16" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_17" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_18" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_19" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
foo = Cylinder name:"sbarra_6_20" radius:1.0 height:80.0 heightsegs:1 sides:16
foo.material = meditMaterials[1]
addModifier foo mappac
rotate foo rotazionesbarra
foo.position = $hlp_origine_sbarre.position
$sbarra_1_1.pivot = [150, 1137.5, 102]
$sbarra_1_2.pivot = [150, 1122.5, 102]
$sbarra_1_3.pivot = [150, 1107.5, 102]
$sbarra_1_4.pivot = [150, 1092.5, 102]
$sbarra_1_5.pivot = [150, 1077.5, 102]
$sbarra_1_6.pivot = [150, 1062.5, 102]
$sbarra_1_7.pivot = [150, 1047.5, 102]
$sbarra_1_8.pivot = [150, 1032.5, 102]
$sbarra_1_9.pivot = [150, 1017.5, 102]
$sbarra_1_10.pivot = [150, 1002.5, 102]
$sbarra_1_11.pivot = [150, 987.5, 102]
$sbarra_1_12.pivot = [150, 972.5, 102]
$sbarra_1_13.pivot = [150, 957.5, 102]
$sbarra_1_14.pivot = [150, 942.5, 102]
$sbarra_1_15.pivot = [150, 927.5, 102]
$sbarra_1_16.pivot = [150, 912.5, 102]
$sbarra_1_17.pivot = [150, 897.5, 102]
$sbarra_1_18.pivot = [150, 882.5, 102]
$sbarra_1_19.pivot = [150, 867.5, 102]
$sbarra_1_20.pivot = [150, 852.5, 102]
maxOps.setDefaultTangentType #slow #slow
select $catenaria
at time 0 animate on move $ [0, 0, 0]
at time 10 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 11 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_1
at time 12 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 24 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
at time 25 animate on move $ [0, 0, 0]
at time 35 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 36 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_2
at time 37 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 49 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
at time 50 animate on move $ [0, 0, 0]
at time 60 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 61 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_3
at time 62 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 74 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
at time 75 animate on move $ [0, 0, 0]
at time 85 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 86 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_4
at time 87 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 99 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
at time 100 animate on move $ [0, 0, 0]
at time 110 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 111 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_5
at time 112 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 124 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
at time 125 animate on move $ [0, 0, 0]
at time 135 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 136 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_6
at time 137 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 149 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
at time 150 animate on move $ [0, 0, 0]
at time 160 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 161 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_7
at time 162 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 174 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
at time 175 animate on move $ [0, 0, 0]
at time 185 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 186 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_8
at time 187 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 199 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
at time 200 animate on move $ [0, 0, 0]
at time 210 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 211 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_9
at time 212 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 224 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
at time 225 animate on move $ [0, 0, 0]
at time 235 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 236 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_10
at time 237 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 249 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
at time 250 animate on move $ [0, 0, 0]
at time 260 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 261 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_11
at time 262 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 274 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
selectMore $sbarra_1_11
at time 275 animate on move $ [0, 0, 0]
at time 285 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 286 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_12
at time 287 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 299 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
selectMore $sbarra_1_11
selectMore $sbarra_1_12
at time 300 animate on move $ [0, 0, 0]
at time 310 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 311 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_13
at time 312 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 324 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
selectMore $sbarra_1_11
selectMore $sbarra_1_12
selectMore $sbarra_1_13
at time 325 animate on move $ [0, 0, 0]
at time 335 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 336 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_14
at time 337 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 349 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
selectMore $sbarra_1_11
selectMore $sbarra_1_12
selectMore $sbarra_1_13
selectMore $sbarra_1_14
at time 350 animate on move $ [0, 0, 0]
at time 360 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 361 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_15
at time 362 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 374 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
selectMore $sbarra_1_11
selectMore $sbarra_1_12
selectMore $sbarra_1_13
selectMore $sbarra_1_14
selectMore $sbarra_1_15
at time 375 animate on move $ [0, 0, 0]
at time 385 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 386 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_16
at time 387 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 399 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
selectMore $sbarra_1_11
selectMore $sbarra_1_12
selectMore $sbarra_1_13
selectMore $sbarra_1_14
selectMore $sbarra_1_15
selectMore $sbarra_1_16
at time 400 animate on move $ [0, 0, 0]
at time 410 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 411 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_17
at time 412 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 424 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
selectMore $sbarra_1_11
selectMore $sbarra_1_12
selectMore $sbarra_1_13
selectMore $sbarra_1_14
selectMore $sbarra_1_15
selectMore $sbarra_1_16
selectMore $sbarra_1_17
at time 425 animate on move $ [0, 0, 0]
at time 435 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 436 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_18
at time 437 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 449 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
selectMore $sbarra_1_11
selectMore $sbarra_1_12
selectMore $sbarra_1_13
selectMore $sbarra_1_14
selectMore $sbarra_1_15
selectMore $sbarra_1_16
selectMore $sbarra_1_17
selectMore $sbarra_1_18
at time 450 animate on move $ [0, 0, 0]
at time 460 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 461 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_19
at time 462 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 474 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_1_1
selectMore $sbarra_1_2
selectMore $sbarra_1_3
selectMore $sbarra_1_4
selectMore $sbarra_1_5
selectMore $sbarra_1_6
selectMore $sbarra_1_7
selectMore $sbarra_1_8
selectMore $sbarra_1_9
selectMore $sbarra_1_10
selectMore $sbarra_1_11
selectMore $sbarra_1_12
selectMore $sbarra_1_13
selectMore $sbarra_1_14
selectMore $sbarra_1_15
selectMore $sbarra_1_16
selectMore $sbarra_1_17
selectMore $sbarra_1_18
selectMore $sbarra_1_19
at time 475 animate on move $ [0, 0, 0]
at time 485 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 486 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_1_20
at time 487 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 499 animate on move $ [0, -72.5, - 57.2]
clearSelection()
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $ctl_t1_y
selectMore $ctl_t2_y
at time 501 animate on move $ [0, 0, 0]
at time 550 animate on move $ [0, 630, 0]
select $ctl_t1_z
selectMore $ctl_t2_z
at time 551 animate on move $ [0, 0, 0]
at time 575 animate on move $ [0, 0, -125]
select $ctl_t1_z
selectMore $ctl_t2_z
selectMore $sbarra_1*
at time 576 animate on move $ [0, 0, 0]
at time 600 animate on move $ [0, 0, 125]
select $ctl_t1_y
selectMore $ctl_t2_y
selectMore $sbarra_1*
at time 601 animate on move $ [0, 0, 0]
at time 650 animate on move $ [0, -630, 0]
select $ctl_t1_z
selectMore $ctl_t2_z
selectMore $sbarra_1*
at time 651 animate on move $ [0, 0, 0]
at time 675 animate on move $ [0, 0, -103]
select $ctl_t1_z
selectMore $ctl_t2_z
at time 676 animate on move $ [0, 0, 0]
at time 700 animate on move $ [0, 0, 103]
$sbarra_2_1.pivot = [150, 1137.5, 102]
$sbarra_2_2.pivot = [150, 1122.5, 102]
$sbarra_2_3.pivot = [150, 1107.5, 102]
$sbarra_2_4.pivot = [150, 1092.5, 102]
$sbarra_2_5.pivot = [150, 1077.5, 102]
$sbarra_2_6.pivot = [150, 1062.5, 102]
$sbarra_2_7.pivot = [150, 1047.5, 102]
$sbarra_2_8.pivot = [150, 1032.5, 102]
$sbarra_2_9.pivot = [150, 1017.5, 102]
$sbarra_2_10.pivot = [150, 1002.5, 102]
$sbarra_2_11.pivot = [150, 987.5, 102]
$sbarra_2_12.pivot = [150, 972.5, 102]
$sbarra_2_13.pivot = [150, 957.5, 102]
$sbarra_2_14.pivot = [150, 942.5, 102]
$sbarra_2_15.pivot = [150, 927.5, 102]
$sbarra_2_16.pivot = [150, 912.5, 102]
$sbarra_2_17.pivot = [150, 897.5, 102]
$sbarra_2_18.pivot = [150, 882.5, 102]
$sbarra_2_19.pivot = [150, 867.5, 102]
$sbarra_2_20.pivot = [150, 852.5, 102]
maxOps.setDefaultTangentType #slow #slow
select $catenaria
at time 601 animate on move $ [0, 0, 0]
at time 611 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 612 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_1
at time 613 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 625 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
at time 626 animate on move $ [0, 0, 0]
at time 636 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 637 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_2
at time 638 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 650 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
at time 651 animate on move $ [0, 0, 0]
at time 661 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 662 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_3
at time 663 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 675 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
at time 676 animate on move $ [0, 0, 0]
at time 686 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 687 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_4
at time 688 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 700 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
at time 701 animate on move $ [0, 0, 0]
at time 711 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 712 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_5
at time 713 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 725 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
at time 726 animate on move $ [0, 0, 0]
at time 736 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 737 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_6
at time 738 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 750 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
at time 751 animate on move $ [0, 0, 0]
at time 761 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 762 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_7
at time 763 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 775 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
at time 776 animate on move $ [0, 0, 0]
at time 786 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 787 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_8
at time 788 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 800 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
at time 801 animate on move $ [0, 0, 0]
at time 811 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 812 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_9
at time 813 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 825 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
at time 826 animate on move $ [0, 0, 0]
at time 836 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 837 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_10
at time 838 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 850 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
at time 851 animate on move $ [0, 0, 0]
at time 861 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 862 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_11
at time 863 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 875 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
selectMore $sbarra_2_11
at time 876 animate on move $ [0, 0, 0]
at time 886 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 887 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_12
at time 888 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 900 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
selectMore $sbarra_2_11
selectMore $sbarra_2_12
at time 901 animate on move $ [0, 0, 0]
at time 911 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 912 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_13
at time 913 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 925 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
selectMore $sbarra_2_11
selectMore $sbarra_2_12
selectMore $sbarra_2_13
at time 926 animate on move $ [0, 0, 0]
at time 936 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 937 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_14
at time 938 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 950 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
selectMore $sbarra_2_11
selectMore $sbarra_2_12
selectMore $sbarra_2_13
selectMore $sbarra_2_14
at time 951 animate on move $ [0, 0, 0]
at time 961 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 962 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_15
at time 963 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 975 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
selectMore $sbarra_2_11
selectMore $sbarra_2_12
selectMore $sbarra_2_13
selectMore $sbarra_2_14
selectMore $sbarra_2_15
at time 976 animate on move $ [0, 0, 0]
at time 986 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 987 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_16
at time 988 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1000 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
selectMore $sbarra_2_11
selectMore $sbarra_2_12
selectMore $sbarra_2_13
selectMore $sbarra_2_14
selectMore $sbarra_2_15
selectMore $sbarra_2_16
at time 1001 animate on move $ [0, 0, 0]
at time 1011 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1012 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_17
at time 1013 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1025 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
selectMore $sbarra_2_11
selectMore $sbarra_2_12
selectMore $sbarra_2_13
selectMore $sbarra_2_14
selectMore $sbarra_2_15
selectMore $sbarra_2_16
selectMore $sbarra_2_17
at time 1026 animate on move $ [0, 0, 0]
at time 1036 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1037 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_18
at time 1038 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1050 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
selectMore $sbarra_2_11
selectMore $sbarra_2_12
selectMore $sbarra_2_13
selectMore $sbarra_2_14
selectMore $sbarra_2_15
selectMore $sbarra_2_16
selectMore $sbarra_2_17
selectMore $sbarra_2_18
at time 1051 animate on move $ [0, 0, 0]
at time 1061 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1062 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_19
at time 1063 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1075 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_2_1
selectMore $sbarra_2_2
selectMore $sbarra_2_3
selectMore $sbarra_2_4
selectMore $sbarra_2_5
selectMore $sbarra_2_6
selectMore $sbarra_2_7
selectMore $sbarra_2_8
selectMore $sbarra_2_9
selectMore $sbarra_2_10
selectMore $sbarra_2_11
selectMore $sbarra_2_12
selectMore $sbarra_2_13
selectMore $sbarra_2_14
selectMore $sbarra_2_15
selectMore $sbarra_2_16
selectMore $sbarra_2_17
selectMore $sbarra_2_18
selectMore $sbarra_2_19
at time 1076 animate on move $ [0, 0, 0]
at time 1086 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1087 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_2_20
at time 1088 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1100 animate on move $ [0, -72.5, - 57.2]
clearSelection()
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $ctl_t1_y
selectMore $ctl_t2_y
at time 1201 animate on move $ [0, 0, 0]
at time 1250 animate on move $ [0, 630, 0]
select $ctl_t1_z
selectMore $ctl_t2_z
at time 1251 animate on move $ [0, 0, 0]
at time 1275 animate on move $ [0, 0, -125]
select $ctl_t1_z
selectMore $ctl_t2_z
selectMore $sbarra_2*
at time 1276 animate on move $ [0, 0, 0]
at time 1300 animate on move $ [0, 0, 125]
select $ctl_t1_y
selectMore $ctl_t2_y
selectMore $sbarra_2*
at time 1301 animate on move $ [0, 0, 0]
at time 1350 animate on move $ [0, -630, 0]
select $ctl_t1_z
selectMore $ctl_t2_z
selectMore $sbarra_2*
at time 1351 animate on move $ [0, 0, 0]
at time 1375 animate on move $ [0, 0, -103]
select $ctl_t1_z
selectMore $ctl_t2_z
at time 1376 animate on move $ [0, 0, 0]
at time 1400 animate on move $ [0, 0, 103]
select $ctl_vassoio
selectMore $sbarra_1*
at time 1301 animate on move $ [0, 0, 0]
at time 1325 animate on move $ [-175, 0, 0]
$sbarra_3_1.pivot = [150, 1137.5, 102]
$sbarra_3_2.pivot = [150, 1122.5, 102]
$sbarra_3_3.pivot = [150, 1107.5, 102]
$sbarra_3_4.pivot = [150, 1092.5, 102]
$sbarra_3_5.pivot = [150, 1077.5, 102]
$sbarra_3_6.pivot = [150, 1062.5, 102]
$sbarra_3_7.pivot = [150, 1047.5, 102]
$sbarra_3_8.pivot = [150, 1032.5, 102]
$sbarra_3_9.pivot = [150, 1017.5, 102]
$sbarra_3_10.pivot = [150, 1002.5, 102]
$sbarra_3_11.pivot = [150, 987.5, 102]
$sbarra_3_12.pivot = [150, 972.5, 102]
$sbarra_3_13.pivot = [150, 957.5, 102]
$sbarra_3_14.pivot = [150, 942.5, 102]
$sbarra_3_15.pivot = [150, 927.5, 102]
$sbarra_3_16.pivot = [150, 912.5, 102]
$sbarra_3_17.pivot = [150, 897.5, 102]
$sbarra_3_18.pivot = [150, 882.5, 102]
$sbarra_3_19.pivot = [150, 867.5, 102]
$sbarra_3_20.pivot = [150, 852.5, 102]
maxOps.setDefaultTangentType #slow #slow
select $catenaria
at time 1301 animate on move $ [0, 0, 0]
at time 1311 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1312 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_1
at time 1313 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1325 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
at time 1326 animate on move $ [0, 0, 0]
at time 1336 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1337 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_2
at time 1338 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1350 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
at time 1351 animate on move $ [0, 0, 0]
at time 1361 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1362 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_3
at time 1363 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1375 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
at time 1376 animate on move $ [0, 0, 0]
at time 1386 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1387 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_4
at time 1388 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1400 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
at time 1401 animate on move $ [0, 0, 0]
at time 1411 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1412 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_5
at time 1413 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1425 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
at time 1426 animate on move $ [0, 0, 0]
at time 1436 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1437 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_6
at time 1438 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1450 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
at time 1451 animate on move $ [0, 0, 0]
at time 1461 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1462 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_7
at time 1463 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1475 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
at time 1476 animate on move $ [0, 0, 0]
at time 1486 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1487 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_8
at time 1488 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1500 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
at time 1501 animate on move $ [0, 0, 0]
at time 1511 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1512 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_9
at time 1513 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1525 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
at time 1526 animate on move $ [0, 0, 0]
at time 1536 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1537 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_10
at time 1538 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1550 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
at time 1551 animate on move $ [0, 0, 0]
at time 1561 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1562 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_11
at time 1563 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1575 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
selectMore $sbarra_3_11
at time 1576 animate on move $ [0, 0, 0]
at time 1586 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1587 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_12
at time 1588 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1600 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
selectMore $sbarra_3_11
selectMore $sbarra_3_12
at time 1601 animate on move $ [0, 0, 0]
at time 1611 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1612 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_13
at time 1613 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1625 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
selectMore $sbarra_3_11
selectMore $sbarra_3_12
selectMore $sbarra_3_13
at time 1626 animate on move $ [0, 0, 0]
at time 1636 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1637 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_14
at time 1638 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1650 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
selectMore $sbarra_3_11
selectMore $sbarra_3_12
selectMore $sbarra_3_13
selectMore $sbarra_3_14
at time 1651 animate on move $ [0, 0, 0]
at time 1661 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1662 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_15
at time 1663 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1675 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
selectMore $sbarra_3_11
selectMore $sbarra_3_12
selectMore $sbarra_3_13
selectMore $sbarra_3_14
selectMore $sbarra_3_15
at time 1676 animate on move $ [0, 0, 0]
at time 1686 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1687 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_16
at time 1688 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1700 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
selectMore $sbarra_3_11
selectMore $sbarra_3_12
selectMore $sbarra_3_13
selectMore $sbarra_3_14
selectMore $sbarra_3_15
selectMore $sbarra_3_16
at time 1701 animate on move $ [0, 0, 0]
at time 1711 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1712 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_17
at time 1713 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1725 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
selectMore $sbarra_3_11
selectMore $sbarra_3_12
selectMore $sbarra_3_13
selectMore $sbarra_3_14
selectMore $sbarra_3_15
selectMore $sbarra_3_16
selectMore $sbarra_3_17
at time 1726 animate on move $ [0, 0, 0]
at time 1736 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1737 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_18
at time 1738 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1750 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
selectMore $sbarra_3_11
selectMore $sbarra_3_12
selectMore $sbarra_3_13
selectMore $sbarra_3_14
selectMore $sbarra_3_15
selectMore $sbarra_3_16
selectMore $sbarra_3_17
selectMore $sbarra_3_18
at time 1751 animate on move $ [0, 0, 0]
at time 1761 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1762 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_19
at time 1763 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1775 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_3_1
selectMore $sbarra_3_2
selectMore $sbarra_3_3
selectMore $sbarra_3_4
selectMore $sbarra_3_5
selectMore $sbarra_3_6
selectMore $sbarra_3_7
selectMore $sbarra_3_8
selectMore $sbarra_3_9
selectMore $sbarra_3_10
selectMore $sbarra_3_11
selectMore $sbarra_3_12
selectMore $sbarra_3_13
selectMore $sbarra_3_14
selectMore $sbarra_3_15
selectMore $sbarra_3_16
selectMore $sbarra_3_17
selectMore $sbarra_3_18
selectMore $sbarra_3_19
at time 1776 animate on move $ [0, 0, 0]
at time 1786 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 1787 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_3_20
at time 1788 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 1800 animate on move $ [0, -72.5, - 57.2]
clearSelection()
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $ctl_t1_y
at time 1901 animate on move $ [0, 0, 0]
at time 1950 animate on move $ [0, 630, 0]
select $ctl_t1_z
at time 1951 animate on move $ [0, 0, 0]
at time 1975 animate on move $ [0, 0, -125]
select $ctl_t1_z
selectMore $sbarra_3*
at time 1976 animate on move $ [0, 0, 0]
at time 2000 animate on move $ [0, 0, 125]
select $ctl_t1_y
selectMore $sbarra_3*
at time 2001 animate on move $ [0, 0, 0]
at time 2050 animate on move $ [0, -630, 0]
select $ctl_t1_z
selectMore $sbarra_3*
at time 2051 animate on move $ [0, 0, 0]
at time 2075 animate on move $ [0, 0, -103]
select $ctl_t1_z
at time 2076 animate on move $ [0, 0, 0]
at time 2100 animate on move $ [0, 0, 103]
select $ctl_vassoio
selectMore $sbarra_1*
selectMore $sbarra_2*
at time 2001 animate on move $ [0, 0, 0]
at time 2033 animate on move $ [-225, 0, 0]
$sbarra_4_1.pivot = [150, 1137.5, 102]
$sbarra_4_2.pivot = [150, 1122.5, 102]
$sbarra_4_3.pivot = [150, 1107.5, 102]
$sbarra_4_4.pivot = [150, 1092.5, 102]
$sbarra_4_5.pivot = [150, 1077.5, 102]
$sbarra_4_6.pivot = [150, 1062.5, 102]
$sbarra_4_7.pivot = [150, 1047.5, 102]
$sbarra_4_8.pivot = [150, 1032.5, 102]
$sbarra_4_9.pivot = [150, 1017.5, 102]
$sbarra_4_10.pivot = [150, 1002.5, 102]
$sbarra_4_11.pivot = [150, 987.5, 102]
$sbarra_4_12.pivot = [150, 972.5, 102]
$sbarra_4_13.pivot = [150, 957.5, 102]
$sbarra_4_14.pivot = [150, 942.5, 102]
$sbarra_4_15.pivot = [150, 927.5, 102]
$sbarra_4_16.pivot = [150, 912.5, 102]
$sbarra_4_17.pivot = [150, 897.5, 102]
$sbarra_4_18.pivot = [150, 882.5, 102]
$sbarra_4_19.pivot = [150, 867.5, 102]
$sbarra_4_20.pivot = [150, 852.5, 102]
maxOps.setDefaultTangentType #slow #slow
select $catenaria
at time 2001 animate on move $ [0, 0, 0]
at time 2011 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2012 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_1
at time 2013 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2025 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
at time 2026 animate on move $ [0, 0, 0]
at time 2036 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2037 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_2
at time 2038 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2050 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
at time 2051 animate on move $ [0, 0, 0]
at time 2061 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2062 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_3
at time 2063 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2075 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
at time 2076 animate on move $ [0, 0, 0]
at time 2086 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2087 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_4
at time 2088 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2100 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
at time 2101 animate on move $ [0, 0, 0]
at time 2111 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2112 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_5
at time 2113 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2125 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
at time 2126 animate on move $ [0, 0, 0]
at time 2136 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2137 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_6
at time 2138 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2150 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
at time 2151 animate on move $ [0, 0, 0]
at time 2161 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2162 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_7
at time 2163 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2175 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
at time 2176 animate on move $ [0, 0, 0]
at time 2186 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2187 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_8
at time 2188 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2200 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
at time 2201 animate on move $ [0, 0, 0]
at time 2211 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2212 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_9
at time 2213 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2225 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
at time 2226 animate on move $ [0, 0, 0]
at time 2236 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2237 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_10
at time 2238 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2250 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
at time 2251 animate on move $ [0, 0, 0]
at time 2261 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2262 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_11
at time 2263 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2275 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
selectMore $sbarra_4_11
at time 2276 animate on move $ [0, 0, 0]
at time 2286 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2287 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_12
at time 2288 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2300 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
selectMore $sbarra_4_11
selectMore $sbarra_4_12
at time 2301 animate on move $ [0, 0, 0]
at time 2311 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2312 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_13
at time 2313 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2325 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
selectMore $sbarra_4_11
selectMore $sbarra_4_12
selectMore $sbarra_4_13
at time 2326 animate on move $ [0, 0, 0]
at time 2336 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2337 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_14
at time 2338 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2350 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
selectMore $sbarra_4_11
selectMore $sbarra_4_12
selectMore $sbarra_4_13
selectMore $sbarra_4_14
at time 2351 animate on move $ [0, 0, 0]
at time 2361 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2362 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_15
at time 2363 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2375 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
selectMore $sbarra_4_11
selectMore $sbarra_4_12
selectMore $sbarra_4_13
selectMore $sbarra_4_14
selectMore $sbarra_4_15
at time 2376 animate on move $ [0, 0, 0]
at time 2386 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2387 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_16
at time 2388 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2400 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
selectMore $sbarra_4_11
selectMore $sbarra_4_12
selectMore $sbarra_4_13
selectMore $sbarra_4_14
selectMore $sbarra_4_15
selectMore $sbarra_4_16
at time 2401 animate on move $ [0, 0, 0]
at time 2411 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2412 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_17
at time 2413 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2425 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
selectMore $sbarra_4_11
selectMore $sbarra_4_12
selectMore $sbarra_4_13
selectMore $sbarra_4_14
selectMore $sbarra_4_15
selectMore $sbarra_4_16
selectMore $sbarra_4_17
at time 2426 animate on move $ [0, 0, 0]
at time 2436 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2437 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_18
at time 2438 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2450 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
selectMore $sbarra_4_11
selectMore $sbarra_4_12
selectMore $sbarra_4_13
selectMore $sbarra_4_14
selectMore $sbarra_4_15
selectMore $sbarra_4_16
selectMore $sbarra_4_17
selectMore $sbarra_4_18
at time 2451 animate on move $ [0, 0, 0]
at time 2461 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2462 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_19
at time 2463 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2475 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_4_1
selectMore $sbarra_4_2
selectMore $sbarra_4_3
selectMore $sbarra_4_4
selectMore $sbarra_4_5
selectMore $sbarra_4_6
selectMore $sbarra_4_7
selectMore $sbarra_4_8
selectMore $sbarra_4_9
selectMore $sbarra_4_10
selectMore $sbarra_4_11
selectMore $sbarra_4_12
selectMore $sbarra_4_13
selectMore $sbarra_4_14
selectMore $sbarra_4_15
selectMore $sbarra_4_16
selectMore $sbarra_4_17
selectMore $sbarra_4_18
selectMore $sbarra_4_19
at time 2476 animate on move $ [0, 0, 0]
at time 2486 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2487 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_4_20
at time 2488 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2500 animate on move $ [0, -72.5, - 57.2]
clearSelection()
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $ctl_t1_y
at time 2601 animate on move $ [0, 0, 0]
at time 2650 animate on move $ [0, 630, 0]
select $ctl_t1_z
at time 2651 animate on move $ [0, 0, 0]
at time 2675 animate on move $ [0, 0, -125]
select $ctl_t1_z
selectMore $sbarra_4*
at time 2676 animate on move $ [0, 0, 0]
at time 2700 animate on move $ [0, 0, 125]
ruoto = eulerangles 0 0 90
nruoto = eulerangles 0 0 -90
ruotof = eulerangles 0 0 0
poso = $ctl_t1_rot.pivot
select $sbarra_4*
selectMore $ctl_t1_rot
for i in selection do (
   at time 2701 animate on rotate i ruotof
   at time 2725 animate on rotate i ruoto
   )
select $ctl_t1_y
selectMore $sbarra_4*
select $ctl_t1_y
selectMore $sbarra_4*
at time 2726 animate on move $ [0, 0, 0]
at time 2775 animate on move $ [0, -630, 0]
select $ctl_t1_z
selectMore $sbarra_4*
at time 2776 animate on move $ [0, 0, 0]
at time 2800 animate on move $ [0, 0, -101]
select $ctl_t1_z
at time 2801 animate on move $ [0, 0, 0]
at time 2825 animate on move $ [0, 0, 101]
select $ctl_vassoio
selectMore $sbarra_1*
selectMore $sbarra_2*
selectMore $sbarra_3*
at time 2726 animate on move $ [0, 0, 0]
at time 2782 animate on move $ [390, 0, 0]
$sbarra_5_1.pivot = [150, 1137.5, 102]
$sbarra_5_2.pivot = [150, 1122.5, 102]
$sbarra_5_3.pivot = [150, 1107.5, 102]
$sbarra_5_4.pivot = [150, 1092.5, 102]
$sbarra_5_5.pivot = [150, 1077.5, 102]
$sbarra_5_6.pivot = [150, 1062.5, 102]
$sbarra_5_7.pivot = [150, 1047.5, 102]
$sbarra_5_8.pivot = [150, 1032.5, 102]
$sbarra_5_9.pivot = [150, 1017.5, 102]
$sbarra_5_10.pivot = [150, 1002.5, 102]
$sbarra_5_11.pivot = [150, 987.5, 102]
$sbarra_5_12.pivot = [150, 972.5, 102]
$sbarra_5_13.pivot = [150, 957.5, 102]
$sbarra_5_14.pivot = [150, 942.5, 102]
$sbarra_5_15.pivot = [150, 927.5, 102]
$sbarra_5_16.pivot = [150, 912.5, 102]
$sbarra_5_17.pivot = [150, 897.5, 102]
$sbarra_5_18.pivot = [150, 882.5, 102]
$sbarra_5_19.pivot = [150, 867.5, 102]
$sbarra_5_20.pivot = [150, 852.5, 102]
maxOps.setDefaultTangentType #slow #slow
select $catenaria
at time 2726 animate on move $ [0, 0, 0]
at time 2736 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2737 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_1
at time 2738 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2750 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
at time 2751 animate on move $ [0, 0, 0]
at time 2761 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2762 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_2
at time 2763 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2775 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
at time 2776 animate on move $ [0, 0, 0]
at time 2786 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2787 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_3
at time 2788 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2800 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
at time 2801 animate on move $ [0, 0, 0]
at time 2811 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2812 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_4
at time 2813 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2825 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
at time 2826 animate on move $ [0, 0, 0]
at time 2836 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2837 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_5
at time 2838 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2850 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
at time 2851 animate on move $ [0, 0, 0]
at time 2861 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2862 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_6
at time 2863 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2875 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
at time 2876 animate on move $ [0, 0, 0]
at time 2886 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2887 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_7
at time 2888 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2900 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
at time 2901 animate on move $ [0, 0, 0]
at time 2911 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2912 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_8
at time 2913 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2925 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
at time 2926 animate on move $ [0, 0, 0]
at time 2936 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2937 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_9
at time 2938 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2950 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
at time 2951 animate on move $ [0, 0, 0]
at time 2961 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2962 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_10
at time 2963 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 2975 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
at time 2976 animate on move $ [0, 0, 0]
at time 2986 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 2987 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_11
at time 2988 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3000 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
selectMore $sbarra_5_11
at time 3001 animate on move $ [0, 0, 0]
at time 3011 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3012 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_12
at time 3013 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3025 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
selectMore $sbarra_5_11
selectMore $sbarra_5_12
at time 3026 animate on move $ [0, 0, 0]
at time 3036 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3037 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_13
at time 3038 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3050 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
selectMore $sbarra_5_11
selectMore $sbarra_5_12
selectMore $sbarra_5_13
at time 3051 animate on move $ [0, 0, 0]
at time 3061 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3062 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_14
at time 3063 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3075 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
selectMore $sbarra_5_11
selectMore $sbarra_5_12
selectMore $sbarra_5_13
selectMore $sbarra_5_14
at time 3076 animate on move $ [0, 0, 0]
at time 3086 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3087 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_15
at time 3088 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3100 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
selectMore $sbarra_5_11
selectMore $sbarra_5_12
selectMore $sbarra_5_13
selectMore $sbarra_5_14
selectMore $sbarra_5_15
at time 3101 animate on move $ [0, 0, 0]
at time 3111 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3112 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_16
at time 3113 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3125 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
selectMore $sbarra_5_11
selectMore $sbarra_5_12
selectMore $sbarra_5_13
selectMore $sbarra_5_14
selectMore $sbarra_5_15
selectMore $sbarra_5_16
at time 3126 animate on move $ [0, 0, 0]
at time 3136 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3137 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_17
at time 3138 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3150 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
selectMore $sbarra_5_11
selectMore $sbarra_5_12
selectMore $sbarra_5_13
selectMore $sbarra_5_14
selectMore $sbarra_5_15
selectMore $sbarra_5_16
selectMore $sbarra_5_17
at time 3151 animate on move $ [0, 0, 0]
at time 3161 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3162 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_18
at time 3163 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3175 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
selectMore $sbarra_5_11
selectMore $sbarra_5_12
selectMore $sbarra_5_13
selectMore $sbarra_5_14
selectMore $sbarra_5_15
selectMore $sbarra_5_16
selectMore $sbarra_5_17
selectMore $sbarra_5_18
at time 3176 animate on move $ [0, 0, 0]
at time 3186 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3187 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_19
at time 3188 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3200 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_5_1
selectMore $sbarra_5_2
selectMore $sbarra_5_3
selectMore $sbarra_5_4
selectMore $sbarra_5_5
selectMore $sbarra_5_6
selectMore $sbarra_5_7
selectMore $sbarra_5_8
selectMore $sbarra_5_9
selectMore $sbarra_5_10
selectMore $sbarra_5_11
selectMore $sbarra_5_12
selectMore $sbarra_5_13
selectMore $sbarra_5_14
selectMore $sbarra_5_15
selectMore $sbarra_5_16
selectMore $sbarra_5_17
selectMore $sbarra_5_18
selectMore $sbarra_5_19
at time 3201 animate on move $ [0, 0, 0]
at time 3211 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3212 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_5_20
at time 3213 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3225 animate on move $ [0, -72.5, - 57.2]
clearSelection()
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $ctl_t1_y
at time 3326 animate on move $ [0, 0, 0]
at time 3375 animate on move $ [0, 630, 0]
nruoto = eulerangles 0 0 -90
ruotof = eulerangles 0 0 0
at time 3376 animate on rotate $ctl_t1_rot ruotof
at time 3400 animate on rotate $ctl_t1_rot nruoto
select $ctl_t1_z
at time 3401 animate on move $ [0, 0, 0]
at time 3425 animate on move $ [0, 0, -125]
select $ctl_t1_z
selectMore $sbarra_5*
at time 3426 animate on move $ [0, 0, 0]
at time 3450 animate on move $ [0, 0, 125]
ruoto = eulerangles 0 0 90
nruoto = eulerangles 0 0 -90
ruotof = eulerangles 0 0 0
poso = $ctl_t1_rot.pivot
select $sbarra_5*
selectMore $ctl_t1_rot
for i in selection do (
   at time 3451 animate on rotate i ruotof
   at time 3475 animate on rotate i ruoto
   )
select $ctl_t1_y
selectMore $sbarra_5*
select $ctl_t1_y
selectMore $sbarra_5*
at time 3476 animate on move $ [0, 0, 0]
at time 3525 animate on move $ [0, -630, 0]
select $ctl_t1_z
selectMore $sbarra_5*
at time 3526 animate on move $ [0, 0, 0]
at time 3550 animate on move $ [0, 0, -101]
select $ctl_t1_z
at time 3551 animate on move $ [0, 0, 0]
at time 3575 animate on move $ [0, 0, 101]
select $ctl_vassoio
selectMore $sbarra_1*
selectMore $sbarra_2*
selectMore $sbarra_3*
selectMore $sbarra_4*
at time 3476 animate on move $ [0, 0, 0]
at time 3519 animate on move $ [-300, 0, 0]
$sbarra_6_1.pivot = [150, 1137.5, 102]
$sbarra_6_2.pivot = [150, 1122.5, 102]
$sbarra_6_3.pivot = [150, 1107.5, 102]
$sbarra_6_4.pivot = [150, 1092.5, 102]
$sbarra_6_5.pivot = [150, 1077.5, 102]
$sbarra_6_6.pivot = [150, 1062.5, 102]
$sbarra_6_7.pivot = [150, 1047.5, 102]
$sbarra_6_8.pivot = [150, 1032.5, 102]
$sbarra_6_9.pivot = [150, 1017.5, 102]
$sbarra_6_10.pivot = [150, 1002.5, 102]
$sbarra_6_11.pivot = [150, 987.5, 102]
$sbarra_6_12.pivot = [150, 972.5, 102]
$sbarra_6_13.pivot = [150, 957.5, 102]
$sbarra_6_14.pivot = [150, 942.5, 102]
$sbarra_6_15.pivot = [150, 927.5, 102]
$sbarra_6_16.pivot = [150, 912.5, 102]
$sbarra_6_17.pivot = [150, 897.5, 102]
$sbarra_6_18.pivot = [150, 882.5, 102]
$sbarra_6_19.pivot = [150, 867.5, 102]
$sbarra_6_20.pivot = [150, 852.5, 102]
maxOps.setDefaultTangentType #slow #slow
select $catenaria
at time 3476 animate on move $ [0, 0, 0]
at time 3486 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3487 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_1
at time 3488 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3500 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
at time 3501 animate on move $ [0, 0, 0]
at time 3511 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3512 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_2
at time 3513 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3525 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
at time 3526 animate on move $ [0, 0, 0]
at time 3536 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3537 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_3
at time 3538 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3550 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
at time 3551 animate on move $ [0, 0, 0]
at time 3561 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3562 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_4
at time 3563 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3575 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
at time 3576 animate on move $ [0, 0, 0]
at time 3586 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3587 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_5
at time 3588 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3600 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
at time 3601 animate on move $ [0, 0, 0]
at time 3611 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3612 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_6
at time 3613 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3625 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
at time 3626 animate on move $ [0, 0, 0]
at time 3636 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3637 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_7
at time 3638 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3650 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
at time 3651 animate on move $ [0, 0, 0]
at time 3661 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3662 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_8
at time 3663 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3675 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
at time 3676 animate on move $ [0, 0, 0]
at time 3686 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3687 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_9
at time 3688 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3700 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
at time 3701 animate on move $ [0, 0, 0]
at time 3711 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3712 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_10
at time 3713 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3725 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
at time 3726 animate on move $ [0, 0, 0]
at time 3736 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3737 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_11
at time 3738 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3750 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
selectMore $sbarra_6_11
at time 3751 animate on move $ [0, 0, 0]
at time 3761 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3762 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_12
at time 3763 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3775 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
selectMore $sbarra_6_11
selectMore $sbarra_6_12
at time 3776 animate on move $ [0, 0, 0]
at time 3786 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3787 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_13
at time 3788 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3800 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
selectMore $sbarra_6_11
selectMore $sbarra_6_12
selectMore $sbarra_6_13
at time 3801 animate on move $ [0, 0, 0]
at time 3811 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3812 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_14
at time 3813 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3825 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
selectMore $sbarra_6_11
selectMore $sbarra_6_12
selectMore $sbarra_6_13
selectMore $sbarra_6_14
at time 3826 animate on move $ [0, 0, 0]
at time 3836 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3837 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_15
at time 3838 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3850 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
selectMore $sbarra_6_11
selectMore $sbarra_6_12
selectMore $sbarra_6_13
selectMore $sbarra_6_14
selectMore $sbarra_6_15
at time 3851 animate on move $ [0, 0, 0]
at time 3861 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3862 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_16
at time 3863 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3875 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
selectMore $sbarra_6_11
selectMore $sbarra_6_12
selectMore $sbarra_6_13
selectMore $sbarra_6_14
selectMore $sbarra_6_15
selectMore $sbarra_6_16
at time 3876 animate on move $ [0, 0, 0]
at time 3886 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3887 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_17
at time 3888 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3900 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
selectMore $sbarra_6_11
selectMore $sbarra_6_12
selectMore $sbarra_6_13
selectMore $sbarra_6_14
selectMore $sbarra_6_15
selectMore $sbarra_6_16
selectMore $sbarra_6_17
at time 3901 animate on move $ [0, 0, 0]
at time 3911 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3912 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_18
at time 3913 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3925 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
selectMore $sbarra_6_11
selectMore $sbarra_6_12
selectMore $sbarra_6_13
selectMore $sbarra_6_14
selectMore $sbarra_6_15
selectMore $sbarra_6_16
selectMore $sbarra_6_17
selectMore $sbarra_6_18
at time 3926 animate on move $ [0, 0, 0]
at time 3936 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3937 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_19
at time 3938 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3950 animate on move $ [0, -72.5, - 57.2]
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $catenaria
selectMore $sbarra_6_1
selectMore $sbarra_6_2
selectMore $sbarra_6_3
selectMore $sbarra_6_4
selectMore $sbarra_6_5
selectMore $sbarra_6_6
selectMore $sbarra_6_7
selectMore $sbarra_6_8
selectMore $sbarra_6_9
selectMore $sbarra_6_10
selectMore $sbarra_6_11
selectMore $sbarra_6_12
selectMore $sbarra_6_13
selectMore $sbarra_6_14
selectMore $sbarra_6_15
selectMore $sbarra_6_16
selectMore $sbarra_6_17
selectMore $sbarra_6_18
selectMore $sbarra_6_19
at time 3951 animate on move $ [0, 0, 0]
at time 3961 animate on move $ [0, -15.0, 0]
maxOps.setDefaultTangentType #step #step
select $catenaria
at time 3962 animate on move $ [0, 15.0, 0]
maxOps.setDefaultTangentType #slow #slow
select $sbarra_6_20
at time 3963 animate on move $ [0, 0, 0]
maxOps.setDefaultTangentType #slow #linear
at time 3975 animate on move $ [0, -72.5, - 57.2]
clearSelection()
clearSelection()
maxOps.setDefaultTangentType #slow #slow
select $ctl_t1_y
at time 4076 animate on move $ [0, 0, 0]
at time 4125 animate on move $ [0, 630, 0]
nruoto = eulerangles 0 0 -90
ruotof = eulerangles 0 0 0
at time 4126 animate on rotate $ctl_t1_rot ruotof
at time 4150 animate on rotate $ctl_t1_rot nruoto
select $ctl_t1_z
at time 4151 animate on move $ [0, 0, 0]
at time 4175 animate on move $ [0, 0, -125]
select $ctl_t1_z
selectMore $sbarra_6*
at time 4176 animate on move $ [0, 0, 0]
at time 4200 animate on move $ [0, 0, 125]
ruoto = eulerangles 0 0 -90
nruoto = eulerangles 0 0 90
ruotof = eulerangles 0 0 0
poso = $ctl_t1_rot.pivot
select $sbarra_6*
selectMore $ctl_t1_rot
for i in selection do (
   at time 4201 animate on rotate i ruotof
   at time 4225 animate on rotate i ruoto
   )
select $ctl_t1_y
selectMore $sbarra_6*
select $ctl_t1_y
selectMore $sbarra_6*
at time 4226 animate on move $ [0, 0, 0]
at time 4275 animate on move $ [0, -630, 0]
select $ctl_t1_z
selectMore $sbarra_6*
at time 4276 animate on move $ [0, 0, 0]
at time 4300 animate on move $ [0, 0, -103]
select $ctl_t1_z
at time 4301 animate on move $ [0, 0, 0]
at time 4325 animate on move $ [0, 0, 103]
select $ctl_vassoio
selectMore $sbarra_1*
selectMore $sbarra_2*
selectMore $sbarra_3*
selectMore $sbarra_4*
selectMore $sbarra_5*
at time 4226 animate on move $ [0, 0, 0]
at time 4257 animate on move $ [220, 0, 0]
